---
- name: Install td-agent-bit on clients.
  hosts: all
  vars:
    td_agent_version: "td-agent-bit-0.14.1-1.x86_64.rpm"
    src_dir: files/client/stage

  handlers:
  - name: restart td-agent-bit
    systemd:
      name: td-agent-bit
      state: restarted

  tasks:
  - name: Copy RPM file over to the client
    copy:
      src: "files/client/{{ td_agent_version }}"
      dest: /tmp/
    tags: fluent_agent_install

  - name: Install fluent-bit(td-agent-bit) RPM
    yum:
      name: "/tmp/{{ td_agent_version }}"
      state: present
    tags: fluent_agent_install

  - name: Copy td-agent-bit config files for control nodes
    copy: src="{{ src_dir }}/controller/" dest=/etc/td-agent-bit/ mode=0644
    when: ansible_nodename is search('stage-kar-ctl[0-9]{2}')
    notify: restart td-agent-bit
    tags: copy_config_ctl

  - name: Copy td-agent-bit config files for compute nodes
    copy: src="{{ src_dir }}/compute/" dest=/etc/td-agent-bit/ mode=0644
    when: ansible_nodename is search('stage-kar-cmp[0-9]{3}')
    notify: restart td-agent-bit
    tags: copy_config_cmp

  - name: "Copy td-agent-bit config files for ceph-sata nodes"
    copy: src="{{ src_dir }}/ceph-sata/" dest=/etc/td-agent-bit/ mode=0644
    when: ansible_nodename is  search('kar-stage-ceph[0-9]{3}-sata')
    notify: restart td-agent-bit
    tags: copy_config_cephsata

  - name: "Copy td-agent-bit config files for ceph-ssd nodes"
    copy: src="{{ src_dir }}/ceph-ssd/" dest=/etc/td-agent-bit/ mode=0644
    when: ansible_nodename is  search('kar-stage-ceph[0-9]{3}-ssd')
    notify: restart td-agent-bit
    tags: copy_config_cephssd

  - name: Enable and start td-agent-bit service to start at boot up.
    systemd:
      name: td-agent-bit
      enabled: yes
      state: started
...
